### ISSUE TITLE
version 2.4.12. create Permissions and sync issue in server

### ISSUE THREAD

**Issue by srujithogirala** [krathjen/studiolibrary#237] opened 2019-05-30 12:06 UTC
Hi krathjen,

        First of all your tool is amazing. a big life saver. I have a small issue. please check below

 I am getting access denied warning when i am creating any folder, pose or animation in server, even after i am having full permissions in server. it is creating file but not displaying in library. database.json file is not updating but rather it creating a new file, database.json.TMP. Can you please tell me the solution for this? 

In older version (2.3.4)  i dint face this issue. though it used to warn me about access but it used to show the files when i refresh which is not happening in present version.

thanks
Srujith

**Comment by krathjen** [comment] 2019-06-01 13:46
Hi @srujithogirala,

Thanks for submitting the issue.

Yes, it does sound like a permissions issue. I'll also have a look when I get a bit more time.

The `database.json`, `database.json.bak` and `database.json.tmp` files are just a cache, so you could try deleting those files and running the sync again. If you're worried about deleting the files you could just move them to another folder for now.

Let me know if that works.

Cheers,

Kurt

**Comment by srujithogirala** [comment] 2019-06-03 05:38
Thank a lot buddy :)

**Comment by BigRoy** [comment] 2019-07-29 12:30
@krathjen I can confirm that we are running into the same issue. It's still present in the latest 2.5.6 and we're running Windows 10 and have the library on a network share (to which we do have read/write access). The network share is a samba share on a linux server.

Here's some more details.

Usually the errors end up like this:

![studiolibrary_cannot_find_specified_file](https://user-images.githubusercontent.com/2439881/62047545-0fbdeb80-b20b-11e9-9ba7-7597fe5b1aa3.png)
 
Here's one of the tracebacks:
```python
# Traceback (most recent call last):
#   File "P:\pipeline\2.1_dev\git\studiolibrary\src\studioqt\decorators.py", line 24, in wrapped
#     return fn(*args, **kwargs)
#   File "P:\pipeline\2.1_dev\git\studiolibrary\src\studiolibrary\librarywindow.py", line 664, in _sync
#     self.library().sync(progressCallback=self.setProgressBarValue)
#   File "P:\pipeline\2.1_dev\git\studiolibrary\src\studiolibrary\library.py", line 331, in sync
#     self.save(new)
#   File "P:\pipeline\2.1_dev\git\studiolibrary\src\studiolibrary\library.py", line 276, in save
#     studiolibrary.saveJson(self.databasePath(), data)
#   File "P:\pipeline\2.1_dev\git\studiolibrary\src\studiolibrary\utils.py", line 905, in saveJson
#     write(path, data)
#   File "P:\pipeline\2.1_dev\git\studiolibrary\src\studiolibrary\utils.py", line 838, in write
#     os.remove(bak)
# WindowsError: [Error 2] The system cannot find the file specified: u'P:/Projects/projectname/resources/poseLibrary/.studiolibrary/database.json.bak'
```

It seems to happen on everything, saving an animation, renaming, moving to trash. Afterwards it appears as if the command failed and did nothing, however pressing the Refresh button actually shows that it did create/rename/remove as intended.

The interesting bit is that it seems to happen on [this line](https://github.com/krathjen/studiolibrary/blob/48230e2b330d87bc6222fc1cf5e3a56927f81148/src/studiolibrary/utils.py#L838) where prior to it, it actually checks whether the `.bak` file already exists and only if it exists tries to remove it. Plus that in the end just clicking refresh seemingly shows that it did succeed after all.

Even more interesting, if I keep the folder open in Windows Explorer to debug what's happening then all of a sudden it magically works, no errors. This makes me "guess" that somehow `os.path.exists` is incorrectly assuming the file (still) exists as if it's reading some cached path or Python not correctly detecting the contents have updated/changed.

These seem related:
- https://stackoverflow.com/questions/3112546/os-path-exists-lies
- https://stackoverflow.com/questions/29541644/python-os-path-exists-reports-false-when-files-is-there

Maybe the best workaround is to try this:
- https://stackoverflow.com/a/10840586/1838864

**Comment by BigRoy** [comment] 2019-07-29 12:37
I quickly replaced the removal with the `silentremove` function as described here: https://stackoverflow.com/a/10840586/1838864

That does seem to do the trick and avoid the error message.

**Comment by krathjen** [comment] 2019-07-29 13:03
Hi @BigRoy,

Thanks for taking the time to look at this issue. I also found it very interesting reading the answers on StackOverflow as I haven't been able to recreate the error. 

If you have the time please feel free to make a merge request, otherwise, I'm more than happy to make the changes hopefully within the next day or two.

Thanks again.

Kurt

**Comment by BigRoy** [comment] 2019-07-29 13:30
Quickly opened a PR with #243 however definitely test it locally and see if it doesn't introduce other issues. Also, I didn't bump any version nor am I sure whether it fits the required code style you're using (I tried to match it as closely as possible.)

**Comment by krathjen** [comment] 2019-07-29 22:40
Hey @BigRoy,

Thanks for creating the pull request.

I'm a bit busy today but I'll test it locally soon otherwise, it looks great.

Thanks again.

Kurt

**Closed** 2019-07-30 10:22 UTC
